version: '3.8'

services:
  mysqldb:
    image: ${DATABASE_TYPE}:${DATABASE_TYPE_VERSION}
    environment:
      - MYSQL_ROOT_PASSWORD=${DATABASE_PASSWORD}
      - MYSQL_DATABASE=${DATABASE_NAME}
    ports:
      - ${DATABASE_PORT}:3306